// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqsNxztBx1OkgaC5hTaJWiE9AVSRXh2E',
    appId: '1:167447137225:web:68c9ea1ae2ab62f67e3618',
    messagingSenderId: '167447137225',
    projectId: 'specifishapp',
    authDomain: 'specifishapp.firebaseapp.com',
    storageBucket: 'specifishapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHuqn4G8OLMYS-Z--vaw7CZuNNOoSwovU',
    appId: '1:167447137225:android:9cb1e6e58cfcdc1e7e3618',
    messagingSenderId: '167447137225',
    projectId: 'specifishapp',
    storageBucket: 'specifishapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMbCZSJP5Oh5qLHQwrzIfc_hC2rjRffg',
    appId: '1:167447137225:ios:b925b04e80db64f87e3618',
    messagingSenderId: '167447137225',
    projectId: 'specifishapp',
    storageBucket: 'specifishapp.appspot.com',
    iosClientId: '167447137225-mkjr7i1nadl141a352uo23mfb7gur1tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMbCZSJP5Oh5qLHQwrzIfc_hC2rjRffg',
    appId: '1:167447137225:ios:b925b04e80db64f87e3618',
    messagingSenderId: '167447137225',
    projectId: 'specifishapp',
    storageBucket: 'specifishapp.appspot.com',
    iosClientId: '167447137225-mkjr7i1nadl141a352uo23mfb7gur1tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
